### PR TITLE
Deleted confidential data

### PR DESCRIPTION
**Pull request by tweimer**
Never put those in a public git.
Change your password. 
Feel free to delete this PR after.
Also check other files.

### CODE REVIEW

**Comment by Parjanya7** [comment]
Thank you for the update. I really missed that part to gitignore build and .env . However I could not get what you said about deleting PR.  Could you please elaborate ??

And, Please let me know if anything should get changed or updated or made better or added. 

Thank you so much for your kind support.

**Comment by tweimer** [comment]
Well, change your gitignore. I'm not sure if you can delete this Pull Request, so just leave it as it is.

**Comment by Parjanya7** [comment]
Gitignore is already changed. Pull Request is showing 0 by itself. Or I guess, due to you deleted the patch.

Thank You.

**Comment by Parjanya7** [comment]
Gitignore is already changed. Pull Request is showing 0 by itself. Or I guess, due to you deleted the patch.

Thank You.

**Comment by Parjanya7** [comment]
Gitignore is already changed. Pull Request is showing 0 by itself. Or I guess, due to you deleted the patch.

Thank You.

**Pull request merged**
